# Generated by Django 3.2.20 on 2024-11-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=13, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('is_sa_citizen', models.BooleanField()),
                ('search_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('id_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='id_check.idinfo')),
            ],
        ),
    ]
